# Generated by Django 5.2.15 on 2026-06-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_advisory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropadvisoryprediction',
            name='feature_contributions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
